# -*- coding: utf-8 -*-
"""originalaero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WvYf0Q2K2LtUMZzvNtqykO3If4oLjTS
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import cm
import seaborn as sns
from io import BytesIO
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
import warnings
warnings.filterwarnings('ignore')

# Machine Learning Imports (only what we actually use)
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# -----------------------------------------------------------
# 🧠 ML Models & Data Processing
# -----------------------------------------------------------

class AirfoilMLPredictor:
    """Advanced ML model for airfoil aerodynamic prediction"""

    def __init__(self):
        self.models = {
            'lift': None,
            'drag': None,
            'moment': None
        }
        self.scalers = {
            'features': StandardScaler(),
            'lift': StandardScaler(),
            'drag': StandardScaler(),
            'moment': StandardScaler()
        }
        self.is_trained = False

    def extract_geometric_features(self, x, y):
        """Extract comprehensive geometric features from airfoil coordinates"""
        n_points = len(x)

        # Basic geometric parameters
        chord = np.max(x) - np.min(x)
        thickness = np.max(y) - np.min(y)
        max_thickness_idx = np.argmax(np.abs(y))
        max_thickness_pos = x[max_thickness_idx] / chord if chord > 0 else 0

        # Camber analysis
        x_sorted = np.sort(x)
        y_sorted = y[np.argsort(x)]

        # Calculate approximate camber
        x_camber = np.linspace(0, 1, min(50, len(x)//2))
        try:
            y_interp = np.interp(x_camber, x_sorted, y_sorted)
            max_camber = np.max(np.abs(y_interp))
            max_camber_pos = x_camber[np.argmax(np.abs(y_interp))] if len(y_interp) > 0 else 0.5
        except:
            max_camber = thickness * 0.1
            max_camber_pos = 0.4

        # Leading edge characteristics
        le_curvature = abs(y[1] - y[0]) / (x[1] - x[0] + 1e-10) if len(x) > 1 else 0

        # Trailing edge characteristics
        te_angle = np.arctan2(y[-1] - y[-2], x[-1] - x[-2]) if len(x) > 1 else 0

        # Surface characteristics
        try:
            curvature = np.gradient(np.gradient(y, x), x)
            mean_curvature = np.mean(np.abs(curvature[~np.isnan(curvature)]))
            max_curvature = np.max(np.abs(curvature[~np.isnan(curvature)]))
        except:
            mean_curvature = max_curvature = 1.0

        # Area calculation
        area = np.trapz(y, x) if len(x) > 1 else 0

        features = np.array([
            chord, thickness, max_thickness_pos, max_camber, max_camber_pos,
            le_curvature, te_angle, mean_curvature, max_curvature, area,
            len(x)  # number of points
        ])

        return features

    def create_synthetic_dataset(self, n_samples=3000):
        """Create synthetic training dataset based on aerodynamic theory"""
        np.random.seed(42)

        # Generate diverse airfoil parameters
        m_vals = np.random.uniform(0, 0.08, n_samples)
        p_vals = np.random.uniform(0.2, 0.7, n_samples)
        t_vals = np.random.uniform(0.06, 0.25, n_samples)
        alpha_vals = np.random.uniform(-10, 20, n_samples)

        features_list = []
        lift_coeffs = []
        drag_coeffs = []
        moment_coeffs = []

        for i in range(n_samples):
            # Generate airfoil
            x_airfoil, y_airfoil = generate_naca4(m_vals[i], p_vals[i], t_vals[i])
            geom_features = self.extract_geometric_features(x_airfoil, y_airfoil)

            # Add operational parameters
            alpha = alpha_vals[i]
            Re = np.random.uniform(1e5, 5e6)

            all_features = np.concatenate([geom_features, [alpha, Re]])
            features_list.append(all_features)

            # Calculate aerodynamic coefficients
            alpha_rad = np.radians(alpha)

            # Lift coefficient
            Cl_theory = 2*np.pi*alpha_rad
            Cl_camber = 2*np.pi*m_vals[i]
            Cl_total = Cl_theory + Cl_camber

            # Stall effects
            alpha_stall = 12 + 5*t_vals[i] - 10*m_vals[i]
            if abs(alpha) > alpha_stall:
                stall_factor = np.cos(np.pi/2 * min(abs(alpha)/20, 1))
                Cl_total *= stall_factor

            # Drag coefficient
            Cd_profile = 0.006 + 0.02*t_vals[i]**2 + 0.1*m_vals[i]**2
            Cd_induced = Cl_total**2 / (np.pi * 8)
            Cd_total = Cd_profile + Cd_induced

            # Reynolds effects
            if Re < 5e5:
                Cd_total *= (1 + 0.5*(5e5/Re - 1))

            # Moment coefficient
            Cm_total = -0.05 - 0.1*m_vals[i] - 0.02*alpha_rad

            # Add realistic noise
            Cl_total += np.random.normal(0, 0.02)
            Cd_total += np.random.normal(0, 0.001)
            Cm_total += np.random.normal(0, 0.005)

            lift_coeffs.append(Cl_total)
            drag_coeffs.append(max(Cd_total, 0.001))
            moment_coeffs.append(Cm_total)

        return np.array(features_list), np.array(lift_coeffs), np.array(drag_coeffs), np.array(moment_coeffs)

    def train_models(self):
        """Train ML models on synthetic dataset"""
        # Generate training data
        X, y_lift, y_drag, y_moment = self.create_synthetic_dataset()

        # Scale features
        X_scaled = self.scalers['features'].fit_transform(X)
        y_lift_scaled = self.scalers['lift'].fit_transform(y_lift.reshape(-1, 1)).ravel()
        y_drag_scaled = self.scalers['drag'].fit_transform(y_drag.reshape(-1, 1)).ravel()
        y_moment_scaled = self.scalers['moment'].fit_transform(y_moment.reshape(-1, 1)).ravel()

        # Configure models for efficiency
        models_config = {
            'lift': (y_lift_scaled, GradientBoostingRegressor(n_estimators=50, max_depth=5, random_state=42)),
            'drag': (y_drag_scaled, RandomForestRegressor(n_estimators=50, max_depth=6, random_state=42)),
            'moment': (y_moment_scaled, MLPRegressor(hidden_layer_sizes=(32, 16), max_iter=200, random_state=42))
        }

        training_scores = {}

        for coeff_name, (y_data, model) in models_config.items():
            X_train, X_test, y_train, y_test = train_test_split(
                X_scaled, y_data, test_size=0.2, random_state=42
            )

            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)

            self.models[coeff_name] = model
            training_scores[coeff_name] = {
                'r2': r2_score(y_test, y_pred),
                'mse': mean_squared_error(y_test, y_pred)
            }

        self.is_trained = True
        return training_scores

    def predict(self, x, y, alpha, Re=1e6):
        """Predict aerodynamic coefficients"""
        if not self.is_trained:
            raise ValueError("Models not trained yet!")

        geom_features = self.extract_geometric_features(x, y)
        all_features = np.concatenate([geom_features, [alpha, Re]]).reshape(1, -1)

        features_scaled = self.scalers['features'].transform(all_features)

        Cl_scaled = self.models['lift'].predict(features_scaled)[0]
        Cd_scaled = self.models['drag'].predict(features_scaled)[0]
        Cm_scaled = self.models['moment'].predict(features_scaled)[0]

        Cl = self.scalers['lift'].inverse_transform([[Cl_scaled]])[0, 0]
        Cd = self.scalers['drag'].inverse_transform([[Cd_scaled]])[0, 0]
        Cm = self.scalers['moment'].inverse_transform([[Cm_scaled]])[0, 0]

        return Cl, max(Cd, 0.001), Cm


class SmartActuatorPlacement:
    """Intelligent actuator placement using aerodynamic principles"""

    def analyze_pressure_distribution(self, x, y, Cl, alpha):
        """Analyze pressure distribution and identify critical points"""
        n_panels = min(len(x) - 1, 100)  # Limit for efficiency
        x_cp = []
        y_cp = []

        for i in range(0, len(x)-1, max(1, (len(x)-1)//n_panels)):
            if i < len(x) - 1:
                x_cp.append((x[i] + x[i+1]) / 2)
                y_cp.append((y[i] + y[i+1]) / 2)

        x_cp = np.array(x_cp)
        y_cp = np.array(y_cp)

        # Simplified Cp calculation
        alpha_rad = np.radians(alpha)
        Cp = np.zeros_like(x_cp)

        for i, (xi, yi) in enumerate(zip(x_cp, y_cp)):
            s = xi
            if yi >= 0:  # upper surface
                Cp[i] = -2*np.sin(2*np.pi*s + alpha_rad) - alpha_rad*np.sin(np.pi*s)
            else:  # lower surface
                Cp[i] = 2*np.sin(2*np.pi*s - alpha_rad) + alpha_rad*np.sin(np.pi*s)

        return x_cp, y_cp, Cp

    def suggest_actuator_locations(self, x, y, Cl, Cd, alpha):
        """Suggest optimal actuator locations"""
        x_cp, y_cp, Cp = self.analyze_pressure_distribution(x, y, Cl, alpha)

        actuators = []

        # Rule 1: Suction on upper surface where Cp is most negative
        upper_mask = y_cp > 0
        if np.any(upper_mask):
            upper_x = x_cp[upper_mask]
            upper_Cp = Cp[upper_mask]

            if len(upper_Cp) > 0:
                best_suction_idx = np.argmin(upper_Cp)
                suction_x = upper_x[best_suction_idx]
                suction_y = np.interp(suction_x, x, y)

                actuators.append({
                    'type': 'suction',
                    'x': suction_x,
                    'y': suction_y,
                    'strength': -0.7,
                    'effectiveness': abs(upper_Cp[best_suction_idx]),
                    'purpose': 'Boundary layer control'
                })

        # Rule 2: Additional suction near separation point (if high drag)
        if Cd > 0.02:
            sep_x = 0.6 + 0.2 * (Cd - 0.02) / 0.02  # Estimate separation point
            sep_x = min(sep_x, 0.85)
            sep_y = np.interp(sep_x, x, y)

            actuators.append({
                'type': 'suction',
                'x': sep_x,
                'y': sep_y,
                'strength': -0.5,
                'effectiveness': Cd,
                'purpose': 'Separation control'
            })

        # Rule 3: Ejection on lower surface for circulation control
        lower_mask = y_cp < 0
        if np.any(lower_mask):
            lower_x = x_cp[lower_mask]

            if len(lower_x) > 0:
                ejection_x = lower_x[len(lower_x)//2]  # Mid-chord lower surface
                ejection_y = np.interp(ejection_x, x, y)

                actuators.append({
                    'type': 'ejection',
                    'x': ejection_x,
                    'y': ejection_y,
                    'strength': 0.4,
                    'effectiveness': 0.5,
                    'purpose': 'Circulation enhancement'
                })

        return actuators

    def estimate_control_effectiveness(self, actuators, baseline_coeffs):
        """Estimate the effectiveness of proposed actuator configuration"""
        Cl_base, Cd_base, Cm_base = baseline_coeffs

        delta_Cl = 0
        delta_Cd = 0
        delta_Cm = 0

        for actuator in actuators:
            x_act = actuator['x']
            strength = abs(actuator['strength'])

            if actuator['type'] == 'suction':
                delta_Cl += 0.25 * strength * (1 - x_act)
                delta_Cd -= 0.03 * strength * x_act
                delta_Cm += 0.015 * strength * (x_act - 0.25)
            elif actuator['type'] == 'ejection':
                delta_Cl -= 0.08 * strength
                delta_Cd -= 0.015 * strength
                delta_Cm -= 0.008 * strength

        return {
            'Cl_controlled': Cl_base + delta_Cl,
            'Cd_controlled': max(Cd_base + delta_Cd, 0.001),
            'Cm_controlled': Cm_base + delta_Cm,
            'delta_Cl': delta_Cl,
            'delta_Cd': delta_Cd,
            'delta_Cm': delta_Cm,
            'L_D_improvement': ((Cl_base + delta_Cl)/(max(Cd_base + delta_Cd, 0.001))) / (Cl_base/Cd_base) - 1
        }


# -----------------------------------------------------------
# 🔧 Core Utility Functions
# -----------------------------------------------------------

def generate_naca4(m, p, t, n=150):
    """Generate NACA 4-digit airfoil coordinates"""
    beta = np.linspace(0, np.pi, n)
    x = 0.5 * (1 - np.cos(beta))

    # Thickness distribution
    yt = 5 * t * (0.2969*np.sqrt(x) - 0.1260*x - 0.3516*x**2 +
                  0.2843*x**3 - 0.1015*x**4)

    # Camber line
    yc = np.zeros_like(x)
    dyc_dx = np.zeros_like(x)

    if p > 0:
        mask1 = x < p
        yc[mask1] = m/p**2 * (2*p*x[mask1] - x[mask1]**2)
        dyc_dx[mask1] = 2*m/p**2 * (p - x[mask1])

        mask2 = x >= p
        yc[mask2] = m/(1-p)**2 * ((1-2*p) + 2*p*x[mask2] - x[2]**2)
        dyc_dx[mask2] = 2*m/(1-p)**2 * (p - x[mask2])

    # Surface coordinates
    theta = np.arctan(dyc_dx)
    xu = x - yt*np.sin(theta)
    yu = yc + yt*np.cos(theta)
    xl = x + yt*np.sin(theta)
    yl = yc - yt*np.cos(theta)

    x_coords = np.concatenate([xu[::-1], xl[1:]])
    y_coords = np.concatenate([yu[::-1], yl[1:]])

    return x_coords, y_coords


def load_dat_file(uploaded_file):
    """Load airfoil coordinates from DAT file"""
    try:
        content = uploaded_file.read().decode('utf-8')
        lines = content.strip().split('\n')

        # Parse coordinate data
        data_lines = []
        airfoil_name = lines[0].strip() if lines else "Unknown Airfoil"

        for line in lines[1:]:
            line = line.strip()
            if line and not line.startswith('#'):
                parts = line.split()
                if len(parts) >= 2:
                    try:
                        x_val = float(parts[0])
                        y_val = float(parts[1])
                        data_lines.append([x_val, y_val])
                    except ValueError:
                        continue

        if len(data_lines) < 10:
            raise ValueError("Insufficient coordinate points")

        data = np.array(data_lines)
        x, y = data[:, 0], data[:, 1]

        # Normalize
        chord = np.max(x) - np.min(x)
        if chord > 0:
            x = (x - np.min(x)) / chord

        return x, y, airfoil_name

    except Exception as e:
        return None, None, str(e)


def enhanced_polar_analysis(predictor, x, y, Re=1e6):
    """Generate comprehensive polar curves"""
    alpha_range = np.linspace(-10, 20, 21)  # Reduced for efficiency
    Cl_vals, Cd_vals, Cm_vals = [], [], []

    for alpha in alpha_range:
        Cl, Cd, Cm = predictor.predict(x, y, alpha, Re)
        Cl_vals.append(Cl)
        Cd_vals.append(Cd)
        Cm_vals.append(Cm)

    Cl_vals = np.array(Cl_vals)
    Cd_vals = np.array(Cd_vals)
    Cm_vals = np.array(Cm_vals)

    L_D_ratio = Cl_vals / Cd_vals
    max_LD_idx = np.argmax(L_D_ratio)
    stall_idx = np.argmax(Cl_vals)

    return {
        'alpha': alpha_range,
        'Cl': Cl_vals,
        'Cd': Cd_vals,
        'Cm': Cm_vals,
        'L_D': L_D_ratio,
        'max_LD_alpha': alpha_range[max_LD_idx],
        'max_LD_value': L_D_ratio[max_LD_idx],
        'stall_alpha': alpha_range[stall_idx],
        'max_Cl': Cl_vals[stall_idx]
    }


def plot_airfoil_analysis(x, y, actuators=None, title="Airfoil Analysis"):
    """Create comprehensive airfoil analysis plot"""
    fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(14, 10))

    # Main geometry
    ax1.plot(x, y, 'k-', linewidth=2, label='Airfoil')
    if actuators:
        for i, actuator in enumerate(actuators):
            color = 'blue' if actuator['type'] == 'suction' else 'red'
            marker = 'v' if actuator['type'] == 'suction' else '^'
            ax1.scatter(actuator['x'], actuator['y'], c=color, s=120,
                       marker=marker, edgecolors='black', linewidth=2,
                       label=f"{actuator['type'].title()} {i+1}")
    ax1.set_aspect('equal')
    ax1.set_title('Geometry & Actuators')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # Thickness distribution
    x_thick = np.linspace(0, 1, 50)
    thickness = []
    for xi in x_thick:
        y_at_x = y[np.abs(x - xi) < 0.02]
        if len(y_at_x) > 1:
            thickness.append(np.max(y_at_x) - np.min(y_at_x))
        else:
            thickness.append(0)

    ax2.plot(x_thick, thickness, 'g-', linewidth=2)
    ax2.set_xlabel('x/c')
    ax2.set_ylabel('Thickness')
    ax2.set_title('Thickness Distribution')
    ax2.grid(True, alpha=0.3)

    # Flow streamlines (simplified)
    X, Y = np.meshgrid(np.linspace(-0.2, 1.2, 50), np.linspace(-0.3, 0.3, 30))
    U = np.ones_like(X)
    V = np.zeros_like(Y)

    # Add circulation effect
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            dx = X[i, j] - 0.25
            dy = Y[i, j]
            r = np.sqrt(dx**2 + dy**2)
            if r > 0.05:
                circulation = 0.3
                U[i, j] += -circulation * dy / (2*np.pi*r**2)
                V[i, j] += circulation * dx / (2*np.pi*r**2)

    strm = ax3.streamplot(X, Y, U, V, density=1.0, color='blue', linewidth=1)
    ax3.plot(x, y, 'k-', linewidth=2)
    ax3.set_xlim(-0.1, 1.1)
    ax3.set_ylim(-0.25, 0.25)
    ax3.set_aspect('equal')
    ax3.set_title('Flow Streamlines')

    if actuators:
        ax3.legend() # Changed from ax.legend()

    plt.colorbar(strm.lines, ax=ax3, label='Flow Speed') # Changed from ax

    # Actuator effectiveness
    if actuators:
        act_names = [f"{a['type'][0].upper()}{i+1}" for i, a in enumerate(actuators)]
        act_eff = [a['effectiveness'] for a in actuators]
        colors_list = ['blue' if a['type'] == 'suction' else 'red' for a in actuators]

        bars = ax4.bar(act_names, act_eff, color=colors_list, alpha=0.7)
        ax4.set_ylabel('Effectiveness Score')
        ax4.set_title('Actuator Effectiveness')
        ax4.grid(True, alpha=0.3)

        for bar, eff in zip(bars, act_eff):
            ax4.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                     f'{eff:.2f}', ha='center', va='bottom')

    plt.tight_layout()
    return fig


def create_comprehensive_report(geometry_name, airfoil_data, polar_data, actuators, control_effectiveness):
    """Generate comprehensive PDF report"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    elements.append(Paragraph("🚀 Advanced Airfoil Analysis Report", styles['Title']))
    elements.append(Spacer(1, 20))

    # Summary
    elements.append(Paragraph("Executive Summary", styles['Heading2']))
    summary_text = f"""
    Airfoil: {geometry_name}<br/>
    Maximum L/D: {polar_data['max_LD_value']:.1f} at α = {polar_data['max_LD_alpha']:.1f}°<br/>
    Stall Angle: {polar_data['stall_alpha']:.1f}°<br/>
    Actuators: {len(actuators)} locations<br/>
    L/D Improvement: {control_effectiveness['L_D_improvement']*100:.1f}%
    """
    elements.append(Paragraph(summary_text, styles['Normal']))
    elements.append(Spacer(1, 15))

    # Actuator table
    elements.append(Paragraph("Actuator Configuration", styles['Heading2']))

    actuator_data = []
    for i, act in enumerate(actuators):
        actuator_data.append([
            f"{act['type'].title()}",
            f"{act['x']:.3f}",
            f"{act['y']:.3f}",
            f"{act['strength']:.2f}",
            f"{act['purpose']}"
        ])

    if actuator_data:
        actuator_table = Table([['Type', 'x/c', 'y/c', 'Strength', 'Purpose']] + actuator_data)
        actuator_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        elements.append(actuator_table)

    doc.build(elements)
    buffer.seek(0)
    return buffer


# -----------------------------------------------------------
# 🚀 Main Streamlit Application
# -----------------------------------------------------------

def main():
    st.set_page_config(page_title="God-Level Airfoil Analysis", layout="wide", page_icon="✈️")

    # Custom styling
    st.markdown("""
    <style>
    .main-header {
        background: linear-gradient(90deg, #1e3c72 0%, #2a5298 100%);
        padding: 1.5rem;
        border-radius: 10px;
        color: white;
        text-align: center;
        margin-bottom: 2rem;
    }
    .metric-box {
        background: #f8f9fa;
        padding: 1rem;
        border-radius: 8px;
        border-left: 4px solid #007bff;
        margin: 0.5rem 0;
    }
    </style>
    """, unsafe_allow_html=True)

    st.markdown('''
    <div class="main-header">
        <h1>🚀 God-Level Airfoil Analysis System</h1>
        <p>ML-Powered CFD Analysis with Intelligent Actuator Placement</p>
    </div>
    ''', unsafe_allow_html=True)

    # Initialize session state
    if 'ml_predictor' not in st.session_state:
        st.session_state.ml_predictor = AirfoilMLPredictor()
        st.session_state.actuator_placement = SmartActuatorPlacement()
        st.session_state.models_trained = False

    # Sidebar
    st.sidebar.header("⚙️ Analysis Configuration")
    Re = st.sidebar.number_input("Reynolds Number", min_value=1e4, max_value=1e7,
                                value=1e6, format="%.0e")

    # Main application tabs
    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        "📁 Input", "🧠 ML Analysis", "🎯 Actuators", "📊 Performance", "📋 Report"
    ])

    # ---------------------------------------
    # Tab 1: Data Input
    # ---------------------------------------
    with tab1:
        st.header("📁 Airfoil Data Input")

        col1, col2 = st.columns([1, 1])

        with col1:
            input_method = st.radio("Select Input Method:",
                                  ["📤 Upload DAT File", "🔢 NACA Generator"])

            if input_method == "📤 Upload DAT File":
                uploaded_file = st.file_uploader("Choose DAT file", type=['dat', 'txt'])
                if uploaded_file:
                    x, y, airfoil_name = load_dat_file(uploaded_file)
                    if x is not None:
                        st.session_state.x = x
                        st.session_state.y = y
                        st.session_state.geometry_name = airfoil_name
                        st.success(f"✅ Successfully loaded: {airfoil_name}")
                        st.info(f"📊 Coordinates: {len(x)} points")
                    else:
                        st.error(f"❌ Error loading file: {airfoil_name}")

            else:  # NACA Generator
                st.subheader("NACA 4-Digit Parameters")

                col_a, col_b, col_c = st.columns(3)
                with col_a:
                    m = st.number_input("Max Camber (%)", 0, 8, 2) / 100
                with col_b:
                    p = st.number_input("Camber Position", 0, 9, 4) / 10
                with col_c:
                    t = st.number_input("Thickness (%)", 6, 25, 12) / 100

                naca_code = f"NACA {int(m*100):02d}{int(p*10)}{int(t*100):02d}"
                st.write(f"**Generated:** {naca_code}")

                if st.button("🎯 Generate Airfoil", type="primary"):
                    x, y = generate_naca4(m, p, t)
                    st.session_state.x = x
                    st.session_state.y = y
                    st.session_state.geometry_name = naca_code
                    st.success(f"✅ Generated: {naca_code}")

        with col2:
            if 'x' in st.session_state:
                st.subheader("📐 Airfoil Geometry")

                fig, ax = plt.subplots(figsize=(10, 6))
                ax.plot(st.session_state.x, st.session_state.y, 'navy', linewidth=2.5)
                ax.fill_between(st.session_state.x, st.session_state.y, alpha=0.3, color='lightblue')
                ax.set_aspect('equal')
                ax.set_title(f"{st.session_state.geometry_name}", fontsize=14, fontweight='bold')
                ax.grid(True, alpha=0.4)
                ax.set_xlabel('x/c', fontsize=12)
                ax.set_ylabel('y/c', fontsize=12)
                st.pyplot(fig)

                # Geometric properties
                max_thickness = np.max(st.session_state.y) - np.min(st.session_state.y)
                max_camber = np.max(np.abs(st.session_state.y))

                col_a, col_b, col_c = st.columns(3)
                with col_a:
                    st.metric("Max Thickness", f"{max_thickness:.3f}c")
                with col_b:
                    st.metric("Max Camber", f"{max_camber:.3f}c")
                with col_c:
                    st.metric("Data Points", len(st.session_state.x))

    # ---------------------------------------
    # Tab 2: ML Analysis
    # ---------------------------------------
    with tab2:
        st.header("🧠 Machine Learning Aerodynamic Analysis")

        if 'x' not in st.session_state:
            st.error("⚠️ Please load airfoil geometry first!")
            st.stop()

        col1, col2 = st.columns([1, 2])

        with col1:
            st.subheader("🎯 ML Model Training")

            if not st.session_state.models_trained:
                if st.button("🚀 Train ML Models", type="primary"):
                    progress_bar = st.progress(0)
                    status_text = st.empty()

                    status_text.text("Training aerodynamic prediction models...")
                    progress_bar.progress(25)

                    training_scores = st.session_state.ml_predictor.train_models()
                    st.session_state.models_trained = True

                    progress_bar.progress(100)
                    status_text.text("✅ Training complete!")

                    st.success("🎉 ML Models trained successfully!")

                    # Show training metrics
                    for coeff, scores in training_scores.items():
                        st.metric(f"{coeff.title()} R²", f"{scores['r2']:.3f}")
            else:
                st.success("✅ Models ready!")

            st.subheader("🔧 Analysis Parameters")
            alpha = st.slider("Angle of Attack (°)", -15.0, 25.0, 5.0, 0.5)

            if st.session_state.models_trained:
                # Real-time prediction
                Cl, Cd, Cm = st.session_state.ml_predictor.predict(
                    st.session_state.x, st.session_state.y, alpha, Re
                )

                st.session_state.baseline_coeffs = (Cl, Cd, Cm)
                st.session_state.current_alpha = alpha

                st.markdown("### 📊 Current Predictions")

                col_a, col_b = st.columns(2)
                with col_a:
                    st.metric("Lift Coefficient (Cl)", f"{Cl:.4f}")
                    st.metric("Drag Coefficient (Cd)", f"{Cd:.4f}")
                with col_b:
                    st.metric("Moment Coefficient (Cm)", f"{Cm:.4f}")
                    st.metric("L/D Ratio", f"{Cl/Cd:.1f}")

                # Performance assessment
                LD_ratio = Cl/Cd
                if LD_ratio > 50:
                    st.success("🌟 Excellent aerodynamic efficiency!")
                elif LD_ratio > 30:
                    st.info("✅ Good aerodynamic performance")
                else:
                    st.warning("⚠️ Room for improvement in efficiency")

        with col2:
            if st.session_state.models_trained:
                st.subheader("📈 Polar Analysis")

                with st.spinner("Generating polar curves..."):
                    polar_data = enhanced_polar_analysis(
                        st.session_state.ml_predictor,
                        st.session_state.x, st.session_state.y, Re
                    )
                    st.session_state.polar_data = polar_data

                # Plot polars
                fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(12, 10))

                # Lift curve
                ax1.plot(polar_data['alpha'], polar_data['Cl'], 'b-', linewidth=2.5)
                ax1.axvline(x=alpha, color='red', linestyle='--', alpha=0.7, label=f'Current α = {alpha}°')
                ax1.set_xlabel('Angle of Attack (°)')
                ax1.set_ylabel('Cl')
                ax1.set_title('Lift Curve')
                ax1.legend()
                ax1.grid(True, alpha=0.3)

                # Drag polar
                ax2.plot(polar_data['Cd'], polar_data['Cl'], 'r-', linewidth=2.5)
                ax2.scatter(Cd, Cl, c='red', s=100, marker='o', label=f'Current Point')
                ax2.set_xlabel('Cd')
                ax2.set_ylabel('Cl')
                ax2.set_title('Drag Polar')
                ax2.legend()
                ax2.grid(True, alpha=0.3)

                # L/D curve
                ax3.plot(polar_data['alpha'], polar_data['L_D'], 'g-', linewidth=2.5)
                max_LD_idx = np.argmax(polar_data['L_D'])
                ax3.scatter(polar_data['alpha'][max_LD_idx], polar_data['L_D'][max_LD_idx],
                           c='gold', s=150, marker='*', label=f"Max L/D = {polar_data['max_LD_value']:.1f}")
                ax3.axvline(x=alpha, color='red', linestyle='--', alpha=0.7)
                ax3.set_xlabel('Angle of Attack (°)')
                ax3.set_ylabel('L/D Ratio')
                ax3.set_title('Lift-to-Drag Performance')
                ax3.legend()
                ax3.grid(True, alpha=0.3)

                # Moment curve
                ax4.plot(polar_data['alpha'], polar_data['Cm'], 'm-', linewidth=2.5)
                ax4.axhline(y=0, color='k', linestyle='--', alpha=0.5)
                ax4.axvline(x=alpha, color='red', linestyle='--', alpha=0.7)
                ax4.set_xlabel('Angle of Attack (°)')
                ax4.set_ylabel('Cm')
                ax4.set_title('Pitching Moment')
                ax4.grid(True, alpha=0.3)

                plt.tight_layout()
                st.pyplot(fig)

                # Key performance metrics
                st.markdown("### 🏆 Key Performance Metrics")
                col_a, col_b, col_c, col_d = st.columns(4)
                with col_a:
                    st.metric("Optimal L/D", f"{polar_data['max_LD_value']:.1f}",
                             f"@ {polar_data['max_LD_alpha']:.1f}°")
                with col_b:
                    st.metric("Stall Angle", f"{polar_data['stall_alpha']:.1f}°")
                with col_c:
                    st.metric("Max Cl", f"{polar_data['max_Cl']:.3f}")
                with col_d:
                    efficiency_rating = "Excellent" if polar_data['max_LD_value'] > 50 else "Good" if polar_data['max_LD_value'] > 30 else "Fair"
                    st.metric("Efficiency", efficiency_rating)

    # ---------------------------------------
    # Tab 3: Actuator Design
    # ---------------------------------------
    with tab3:
        st.header("🎯 Intelligent Actuator Placement System")

        if 'baseline_coeffs' not in st.session_state:
            st.error("⚠️ Please complete ML analysis first!")
            st.stop()

        col1, col2 = st.columns([1, 2])

        with col1:
            st.subheader("🎛️ Control Configuration")

            control_objective = st.selectbox("Primary Control Objective:", [
                "Maximize L/D Ratio",
                "Increase Lift Coefficient",
                "Reduce Drag Coefficient",
                "Improve Stall Characteristics"
            ])

            max_actuators = st.slider("Maximum Actuators", 1, 5, 3)
            control_authority = st.slider("Control Authority", 0.1, 1.0, 0.7, 0.1)

            if st.button("🎯 Design Actuator System", type="primary"):
                with st.spinner("Analyzing flow physics and optimizing actuator placement..."):
                    # Generate actuator recommendations
                    actuators = st.session_state.actuator_placement.suggest_actuator_locations(
                        st.session_state.x, st.session_state.y,
                        st.session_state.baseline_coeffs[0],
                        st.session_state.baseline_coeffs[1],
                        st.session_state.current_alpha
                    )

                    # Apply control authority scaling
                    for actuator in actuators:
                        actuator['strength'] *= control_authority

                    # Limit number of actuators
                    if len(actuators) > max_actuators:
                        actuators.sort(key=lambda x: x['effectiveness'], reverse=True)
                        actuators = actuators[:max_actuators]

                    st.session_state.actuators = actuators

                    # Calculate control effectiveness
                    control_eff = st.session_state.actuator_placement.estimate_control_effectiveness(
                        actuators, st.session_state.baseline_coeffs
                    )
                    st.session_state.control_effectiveness = control_eff

                st.success(f"✅ Optimized {len(st.session_state.actuators)} actuator system!")

            # Manual actuator adjustment
            if 'actuators' in st.session_state and st.session_state.actuators:
                st.subheader("🔧 Fine-Tune Actuators")

                selected_actuator = st.selectbox(
                    "Select Actuator to Adjust:",
                    range(len(st.session_state.actuators)),
                    format_func=lambda i: f"{st.session_state.actuators[i]['type'].title()} {i+1}"
                )

                if selected_actuator < len(st.session_state.actuators):
                    act = st.session_state.actuators[selected_actuator]

                    new_x = st.slider("x/c position", 0.1, 0.9, act['x'], 0.05)
                    new_strength = st.slider("Strength", -1.0, 1.0, act['strength'], 0.1)

                    if st.button("Update Actuator"):
                        st.session_state.actuators[selected_actuator]['x'] = new_x
                        st.session_state.actuators[selected_actuator]['strength'] = new_strength
                        st.session_state.actuators[selected_actuator]['y'] = np.interp(new_x, st.session_state.x, st.session_state.y)

                        # Recalculate effectiveness
                        control_eff = st.session_state.actuator_placement.estimate_control_effectiveness(
                            st.session_state.actuators, st.session_state.baseline_coeffs
                        )
                        st.session_state.control_effectiveness = control_eff
                        st.success("✅ Actuator updated!")

        with col2:
            if 'actuators' in st.session_state and st.session_state.actuators:
                st.subheader("🎪 Actuator Configuration")

                # Display actuator table
                actuator_data = []
                for i, act in enumerate(st.session_state.actuators):
                    actuator_data.append({
                        'ID': f"{act['type'][0].upper()}{i+1}",
                        'Type': act['type'].title(),
                        'x/c': f"{act['x']:.3f}",
                        'y/c': f"{act['y']:.3f}",
                        'Strength': f"{act['strength']:.2f}",
                        'Purpose': act['purpose']
                    })

                actuator_df = pd.DataFrame(actuator_data)
                st.dataframe(actuator_df, use_container_width=True)

                # Visualization
                fig = plot_airfoil_analysis(
                    st.session_state.x, st.session_state.y,
                    st.session_state.actuators,
                    "Actuator Placement & Analysis"
                )
                st.pyplot(fig)

                # Control effectiveness metrics
                if 'control_effectiveness' in st.session_state:
                    st.subheader("📈 Control Effectiveness")
                    eff = st.session_state.control_effectiveness

                    col_a, col_b, col_c = st.columns(3)
                    with col_a:
                        st.metric("ΔCl", f"{eff['delta_Cl']:+.3f}",
                                 delta=f"{eff['delta_Cl']/st.session_state.baseline_coeffs[0]*100:+.1f}%")
                    with col_b:
                        st.metric("ΔCd", f"{eff['delta_Cd']:+.4f}",
                                 delta=f"{eff['delta_Cd']/st.session_state.baseline_coeffs[1]*100:+.1f}%")
                    with col_c:
                        st.metric("L/D Improvement", f"{eff['L_D_improvement']*100:+.1f}%")

                    # Performance indicator
                    if eff['L_D_improvement'] > 0.1:
                        st.success("🌟 Excellent control effectiveness!")
                    elif eff['L_D_improvement'] > 0.05:
                        st.info("✅ Good control performance")
                    else:
                        st.warning("⚠️ Limited control effectiveness")

    # ---------------------------------------
    # Tab 4: Performance Analysis
    # ---------------------------------------
    with tab4:
        st.header("📊 Advanced Performance Analysis")

        if 'control_effectiveness' not in st.session_state:
            st.error("⚠️ Please complete actuator design first!")
            st.stop()

        # Performance comparison dashboard
        st.subheader("🏁 Baseline vs Controlled Performance")

        baseline = st.session_state.baseline_coeffs
        controlled = st.session_state.control_effectiveness

        # Main performance metrics
        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.metric("Lift Coefficient",
                     f"{controlled['Cl_controlled']:.4f}",
                     delta=f"{controlled['delta_Cl']:+.4f}")
        with col2:
            st.metric("Drag Coefficient",
                     f"{controlled['Cd_controlled']:.4f}",
                     delta=f"{controlled['delta_Cd']:+.4f}")
        with col3:
            st.metric("L/D Ratio",
                     f"{controlled['Cl_controlled']/controlled['Cd_controlled']:.1f}",
                     delta=f"{controlled['L_D_improvement']*100:+.1f}%")
        with col4:
            efficiency_gain = controlled['L_D_improvement'] * 100
            if efficiency_gain > 10:
                st.metric("Efficiency Gain", f"{efficiency_gain:.1f}%", "🚀 Excellent")
            elif efficiency_gain > 5:
                st.metric("Efficiency Gain", f"{efficiency_gain:.1f}%", "✅ Good")
            else:
                st.metric("Efficiency Gain", f"{efficiency_gain:.1f}%", "📈 Moderate")

        # Detailed comparison chart
        st.subheader("📊 Performance Comparison Chart")

        comparison_data = pd.DataFrame({
            'Metric': ['Cl', 'Cd (×100)', 'L/D'],
            'Baseline': [baseline[0], baseline[1]*100, baseline[0]/baseline[1]],
            'Controlled': [controlled['Cl_controlled'], controlled['Cd_controlled']*100,
                          controlled['Cl_controlled']/controlled['Cd_controlled']]
        })

        fig, ax = plt.subplots(figsize=(10, 6))
        x_pos = np.arange(len(comparison_data))
        width = 0.35

        bars1 = ax.bar(x_pos - width/2, comparison_data['Baseline'], width,
                      label='Baseline', color='lightblue', alpha=0.8)
        bars2 = ax.bar(x_pos + width/2, comparison_data['Controlled'], width,
                      label='Controlled', color='lightcoral', alpha=0.8)

        ax.set_xlabel('Performance Metrics')
        ax.set_ylabel('Values')
        ax.set_title('Baseline vs Controlled Performance')
        ax.set_xticks(x_pos)
        ax.set_xticklabels(comparison_data['Metric'])
        ax.legend()
        ax.grid(True, alpha=0.3)

        # Add value labels on bars
        for bars in [bars1, bars2]:
            for bar in bars:
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height + height*0.01,
                       f'{height:.2f}', ha='center', va='bottom')

        st.pyplot(fig)

        # Flow field visualization
        st.subheader("🌊 Flow Field Analysis")

        col1, col2 = st.columns(2)

        with col1:
            st.markdown("**Baseline Flow**")
            fig_baseline = create_flow_visualization(st.session_state.x, st.session_state.y,
                                                   None, st.session_state.current_alpha)
            st.pyplot(fig_baseline)

        with col2:
            st.markdown("**Controlled Flow**")
            fig_controlled = create_flow_visualization(st.session_state.x, st.session_state.y,
                                                     st.session_state.actuators, st.session_state.current_alpha)
            st.pyplot(fig_controlled)

        # Sensitivity analysis
        st.subheader("🔍 Actuator Sensitivity Analysis")

        if st.session_state.actuators:
            # Analyze first actuator sensitivity
            base_actuator = st.session_state.actuators[0]
            strength_range = np.linspace(-1.0, 1.0, 11)
            sensitivity_results = []

            for strength in strength_range:
                modified_actuators = st.session_state.actuators.copy()
                modified_actuators[0] = {**base_actuator, 'strength': strength}

                eff = st.session_state.actuator_placement.estimate_control_effectiveness(
                    modified_actuators, st.session_state.baseline_coeffs
                )

                sensitivity_results.append({
                    'Strength': strength,
                    'ΔCl': eff['delta_Cl'],
                    'ΔCd': eff['delta_Cd'],
                    'L/D_improvement': eff['L_D_improvement']*100
                })

            sens_df = pd.DataFrame(sensitivity_results)

            fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

            ax1.plot(sens_df['Strength'], sens_df['ΔCl'], 'b-', linewidth=2, label='ΔCl')
            ax1.plot(sens_df['Strength'], sens_df['ΔCd']*10, 'r-', linewidth=2, label='ΔCd (×10)')
            ax1.axhline(y=0, color='k', linestyle='--', alpha=0.5)
            ax1.set_xlabel('Actuator Strength')
            ax1.set_ylabel('Coefficient Change')
            ax1.set_title('Force Coefficient Sensitivity')
            ax1.legend()
            ax1.grid(True, alpha=0.3)

            ax2.plot(sens_df['Strength'], sens_df['L/D_improvement'], 'g-', linewidth=2)
            ax2.axhline(y=0, color='k', linestyle='--', alpha=0.5)
            ax2.set_xlabel('Actuator Strength')
            ax2.set_ylabel('L/D Improvement (%)')
            ax2.set_title('Efficiency Sensitivity')
            ax2.grid(True, alpha=0.3)

            plt.tight_layout()
            st.pyplot(fig)

    # ---------------------------------------
    # Tab 5: Report Generation
    # ---------------------------------------
    with tab5:
        st.header("📋 Professional Report Generation")

        if 'control_effectiveness' not in st.session_state:
            st.error("⚠️ Please complete performance analysis first!")
            st.stop()

        col1, col2 = st.columns([1, 1])

        with col1:
            st.subheader("📄 Report Configuration")

            report_sections = st.multiselect("Include Sections:", [
                "Executive Summary",
                "Geometric Analysis",
                "Aerodynamic Performance",
                "Actuator Design",
                "Control Effectiveness",
                "Recommendations"
            ], default=["Executive Summary", "Aerodynamic Performance", "Actuator Design"])

            include_charts = st.checkbox("Include Performance Charts", True)

            if st.button("📊 Generate Professional Report", type="primary"):
                with st.spinner("Generating comprehensive analysis report..."):
                    try:
                        pdf_buffer = create_comprehensive_report(
                            st.session_state.geometry_name,
                            {
                                'x': st.session_state.x,
                                'y': st.session_state.y,
                                'baseline_coeffs': st.session_state.baseline_coeffs
                            },
                            st.session_state.polar_data,
                            st.session_state.actuators,
                            st.session_state.control_effectiveness
                        )

                        st.download_button(
                            "📥 Download PDF Report",
                            data=pdf_buffer,
                            file_name=f"{st.session_state.geometry_name}_analysis_report.pdf",
                            mime="application/pdf",
                            type="primary"
                        )

                        st.success("✅ Report generated successfully!")

                    except Exception as e:
                        st.error(f"❌ Report generation failed: {str(e)}")

        with col2:
            if 'control_effectiveness' in st.session_state:
                st.subheader("📈 Report Preview")

                # Summary statistics
                baseline = st.session_state.baseline_coeffs
                controlled = st.session_state.control_effectiveness

                st.markdown("**Executive Summary Preview:**")

                summary_text = f"""
                **Airfoil:** {st.session_state.geometry_name}
                **Analysis Conditions:** α = {st.session_state.current_alpha:.1f}°, Re = {Re:.0e}

                **Baseline Performance:**
                - Cl = {baseline[0]:.3f}
                - Cd = {baseline[1]:.4f}
                - L/D = {baseline[0]/baseline[1]:.1f}

                **Controlled Performance:**
                - Cl = {controlled['Cl_controlled']:.3f} ({controlled['delta_Cl']:+.3f})
                - Cd = {controlled['Cd_controlled']:.4f} ({controlled['delta_Cd']:+.4f})
                - L/D = {controlled['Cl_controlled']/controlled['Cd_controlled']:.1f} ({controlled['L_D_improvement']*100:+.1f}%)

                **Actuator System:** {len(st.session_state.actuators)} optimally placed actuators
                """

                st.markdown(summary_text)

                # Quick export options
                st.subheader("💾 Quick Export")

                # CSV export of results
                results_data = {
                    'Parameter': ['Cl_baseline', 'Cd_baseline', 'Cm_baseline', 'LD_baseline',
                                 'Cl_controlled', 'Cd_controlled', 'Cm_controlled', 'LD_controlled',
                                 'Delta_Cl', 'Delta_Cd', 'Delta_Cm', 'LD_improvement_percent'],
                    'Value': [baseline[0], baseline[1], baseline[2], baseline[0]/baseline[1],
                             controlled['Cl_controlled'], controlled['Cd_controlled'],
                             controlled['Cm_controlled'], controlled['Cl_controlled']/controlled['Cd_controlled'],
                             controlled['delta_Cl'], controlled['delta_Cd'], controlled['delta_Cm'],
                             controlled['L_D_improvement']*100]
                }

                results_df = pd.DataFrame(results_data)

                csv = results_df.to_csv(index=False)
                st.download_button(
                    "📊 Download Results CSV",
                    data=csv,
                    file_name=f"{st.session_state.geometry_name}_results.csv",
                    mime="text/csv"
                )


# -----------------------------------------------------------
# 🎨 Visualization Functions
# -----------------------------------------------------------

def create_flow_visualization(x, y, actuators=None, alpha=0):
    """Create flow field visualization"""
    fig, ax = plt.subplots(figsize=(8, 5))

    # Create grid
    X, Y = np.meshgrid(np.linspace(-0.2, 1.2, 40), np.linspace(-0.25, 0.25, 25))

    # Initialize flow field
    alpha_rad = np.radians(alpha)
    U = np.cos(alpha_rad) * np.ones_like(X)
    V = np.sin(alpha_rad) * np.ones_like(X)

    # Add basic circulation around airfoil
    circulation = 0.4
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            dx = X[i, j] - 0.25
            dy = Y[i, j]
            r = np.sqrt(dx**2 + dy**2)

            if r > 0.05:
                U[i, j] += -circulation * dy / (2*np.pi*r**2)
                V[i, j] += circulation * dx / (2*np.pi*r**2)

    # Add actuator effects
    if actuators:
        for actuator in actuators:
            ax_pos, ay_pos = actuator['x'], actuator['y']
            strength = actuator['strength'] * 0.1

            for i in range(X.shape[0]):
                for j in range(X.shape[1]):
                    dx = X[i, j] - ax_pos
                    dy = Y[i, j] - ay_pos
                    r = np.sqrt(dx**2 + dy**2)

                    if r > 0.02:
                        U[i, j] += strength * dx / (2*np.pi*r**2)
                        V[i, j] += strength * dy / (2*np.pi*r**2)

    # Plot streamlines
    speed = np.sqrt(U**2 + V**2)
    strm = ax.streamplot(X, Y, U, V, density=1.2, color=speed, cmap='viridis', linewidth=1)

    # Plot airfoil
    ax.plot(x, y, 'k-', linewidth=2.5, label='Airfoil')
    ax.fill_between(x, y, alpha=0.3, color='gray')

    # Plot actuators
    if actuators:
        for i, actuator in enumerate(actuators):
            color = 'blue' if actuator['type'] == 'suction' else 'red'
            marker = 'v' if actuator['type'] == 'suction' else '^'
            ax.scatter(actuator['x'], actuator['y'], c=color, s=120,
                      marker=marker, edgecolors='black', linewidth=2,
                      label=f"{actuator['type'].title()} {i+1}")

    ax.set_xlim(-0.1, 1.1)
    ax.set_ylim(-0.2, 0.2)
    ax.set_aspect('equal')
    ax.set_xlabel('x/c')
    ax.set_ylabel('y/c')
    ax.set_title(f'Flow Field') # Removed alpha as it's not universally available here

    if actuators:
        ax.legend()

    plt.colorbar(strm.lines, ax=ax, label='Flow Speed')

if __name__ == '__main__':
    main()